# Generated by Django 5.0.2 on 2024-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barcold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20000000)),
                ('status', models.CharField(choices=[('df', 'draft'), ('pb', 'published')], default='df', max_length=2)),
            ],
        ),
    ]
